// Mock data for development/testing
import { ROLES, type Student, type Class, type Division, type SchoolSection, type User } from "./types"

export const mockUsers: (User & { password: string })[] = [
  {
    id: 1,
    username: "admin",
    password: "admin123",
    fullName: "System Administrator",
    email: "admin@sunrise.edu",
    phone: "9876543210",
    roleId: ROLES.ADMIN,
    roleName: "Admin",
    isActive: true,
    createdAt: "2024-01-01",
  },
  {
    id: 2,
    username: "parent",
    password: "parent123",
    fullName: "Mr. Sharma",
    email: "parent@email.com",
    phone: "9876543211",
    roleId: ROLES.PARENT,
    roleName: "Parent",
    isActive: true,
    createdAt: "2024-01-15",
  },
  {
    id: 3,
    username: "partner",
    password: "partner123",
    fullName: "ABC Printing Co.",
    email: "partner@print.com",
    phone: "9876543212",
    roleId: ROLES.PARTNER,
    roleName: "Partner",
    isActive: true,
    createdAt: "2024-02-01",
  },
]

export const mockClasses: Class[] = [
  { classId: 1, className: "Class 1", recordStatus: "A" },
  { classId: 2, className: "Class 2", recordStatus: "A" },
  { classId: 3, className: "Class 3", recordStatus: "A" },
  { classId: 4, className: "Class 4", recordStatus: "A" },
  { classId: 5, className: "Class 5", recordStatus: "A" },
  { classId: 6, className: "Class 6", recordStatus: "A" },
  { classId: 7, className: "Class 7", recordStatus: "A" },
  { classId: 8, className: "Class 8", recordStatus: "A" },
  { classId: 9, className: "Class 9", recordStatus: "A" },
  { classId: 10, className: "Class 10", recordStatus: "A" },
]

export const mockDivisions: Division[] = [
  { divisionId: 1, divisionName: "A", classId: 1, recordStatus: "A" },
  { divisionId: 2, divisionName: "B", classId: 1, recordStatus: "A" },
  { divisionId: 3, divisionName: "A", classId: 2, recordStatus: "A" },
  { divisionId: 4, divisionName: "B", classId: 2, recordStatus: "A" },
  { divisionId: 5, divisionName: "A", classId: 3, recordStatus: "A" },
  { divisionId: 6, divisionName: "B", classId: 3, recordStatus: "A" },
  { divisionId: 7, divisionName: "A", classId: 10, recordStatus: "A" },
  { divisionId: 8, divisionName: "B", classId: 10, recordStatus: "A" },
  { divisionId: 9, divisionName: "C", classId: 10, recordStatus: "A" },
]

export const mockSchoolSection: SchoolSection = {
  id: 1,
  tenantName: "CodexPrashantPawar ID Card Management System",
  tenantAddress: "123 Education Lane, Knowledge City, State - 400001",
  tenantPhone: "022-12345678",
  tenantEmail: "info@sunrise-codex.edu",
  logoUrl: "/school-logo-sunrise.jpg",
  recordStatus: "A",
  createdOn: "2024-01-01",
}

export const mockStudents: Student[] = [
  {
    id: 1,
    firstName: "Aarav",
    middleName: "Kumar",
    lastName: "Sharma",
    fullName: "ppppp Kumar Sharma",
    dob: "2012-05-15",
    bloodGroup: "O+",
    classId: 10,
    className: "Class 10",
    divisionId: 7,
    divisionName: "A",
    rollNo: "1001",
    address: "42 Green Park, Mumbai",
    photo: "/student-boy-portrait.jpg",
    parentId: 2,
    parentName: "Mr. Sharma",
    parentPhone: "9876543211",
    emergencyContact: "9876543200",
    status: "Approved",
    recordStatus: "A",
    createdAt: "2024-01-10",
  },
  {
    id: 2,
    firstName: "Priya",
    middleName: "",
    lastName: "Patel",
    fullName: "Priya Patel",
    dob: "2012-08-22",
    bloodGroup: "B+",
    classId: 10,
    className: "Class 10",
    divisionId: 7,
    divisionName: "A",
    rollNo: "1002",
    address: "15 Lotus Colony, Mumbai",
    photo: "/student-girl-portrait.jpg",
    parentId: 4,
    parentName: "Mrs. Patel",
    parentPhone: "9876543213",
    emergencyContact: "9876543201",
    status: "Approved",
    recordStatus: "A",
    createdAt: "2024-01-11",
  },
  {
    id: 3,
    firstName: "Rahul",
    middleName: "Singh",
    lastName: "Verma",
    fullName: "Rahul Singh Verma",
    dob: "2013-02-10",
    bloodGroup: "A+",
    classId: 9,
    className: "Class 9",
    divisionId: 5,
    divisionName: "A",
    rollNo: "901",
    address: "78 Blue Hills, Pune",
    photo: "/indian-student-boy.png",
    parentId: 5,
    parentName: "Mr. Verma",
    parentPhone: "9876543214",
    emergencyContact: "9876543202",
    status: "Pending",
    recordStatus: "A",
    createdAt: "2024-01-12",
  },
  {
    id: 4,
    firstName: "Sneha",
    middleName: "Raj",
    lastName: "Gupta",
    fullName: "Sneha Raj Gupta",
    dob: "2014-11-30",
    bloodGroup: "AB+",
    classId: 8,
    className: "Class 8",
    divisionId: 3,
    divisionName: "A",
    rollNo: "801",
    address: "25 Rose Garden, Delhi",
    photo: "/indian-student-girl.jpg",
    parentId: 6,
    parentName: "Mr. Gupta",
    parentPhone: "9876543215",
    emergencyContact: "9876543203",
    status: "Rejected",
    rejectionReason: "Photo quality is not clear. Please submit a high-resolution passport-size photo.",
    recordStatus: "A",
    createdAt: "2024-01-13",
  },
  {
    id: 5,
    firstName: "Arjun",
    middleName: "",
    lastName: "Reddy",
    fullName: "Arjun Reddy",
    dob: "2012-07-18",
    bloodGroup: "O-",
    classId: 10,
    className: "Class 10",
    divisionId: 8,
    divisionName: "B",
    rollNo: "1003",
    address: "99 Tech Park, Hyderabad",
    photo: "/student-portrait-boy-indian.jpg",
    parentId: 7,
    parentName: "Dr. Reddy",
    parentPhone: "9876543216",
    emergencyContact: "9876543204",
    status: "Approved",
    recordStatus: "A",
    createdAt: "2024-01-14",
  },
]
